
import Header from "@/components/header";
import "./globals.css";
import Footer from "@/components/footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body >
        <Header/>
          {children}
        <Footer/>
        </body>
    </html>
  );
}
